"""Render complete saved answer-audit measurements without further model calls."""
import argparse
import json
from pathlib import Path

from medrag.verification.ragtruth import prepare, score_answers
from medrag.verification.scifact import read_jsonl


def percent(value):
    return "unavailable" if value is None else f"{value:.1%}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, default=Path("data/verification/ragtruth_v1/run01"))
    parser.add_argument("--cache", type=Path, default=Path(".benchmark-runtime/ragtruth"))
    parser.add_argument("--output", type=Path, default=Path("docs/reports/verification-v0.5-answer-audit-results.md"))
    args = parser.parse_args()
    cases, _ = prepare(args.cache)
    rows = read_jsonl(args.run / "predictions.jsonl")
    run = json.loads((args.run / "run.json").read_text(encoding="utf8"))
    if len(rows) != 48 or "completed_utc" not in run:
        raise ValueError("Wait for all 48 attempts; partial runs must not appear complete")
    metrics = {s: score_answers(cases, [r for r in rows if r["strategy"] == s]) for s in ("direct", "split")}
    if metrics != json.loads((args.run / "metrics.json").read_text(encoding="utf8")):
        raise ValueError("Saved metrics differ from current scoring")
    direct, split = metrics["direct"], metrics["split"]
    def fraction(m, numerator, denominator):
        return f"{m['counts'].get(numerator, 0)}/{m['counts'][denominator]}"
    columns = [
        ("Completed answers", lambda m: f"{m['counts']['completed_answers']}/{m['total_answers']}"),
        ("Annotated-error answers flagged (anywhere)", lambda m: fraction(m, "detected_error_answers", "labelled_error_answers")),
        ("Unmarked answers flagged", lambda m: fraction(m, "false_positive_answers", "unmarked_answers")),
        ("Answer error precision", lambda m: percent(m["answer_error_precision"])),
        ("Gold spans: any overlap", lambda m: fraction(m, "span_hit_any", "gold_spans")),
        ("Gold spans: at least half overlap", lambda m: fraction(m, "span_hit_half", "gold_spans")),
        ("Gold spans intersecting extraction", lambda m: fraction(m, "extracted_gold_spans", "gold_spans")),
        ("Non-space character precision", lambda m: percent(m["character_precision"])),
        ("Non-space character recall", lambda m: percent(m["character_recall"])),
        ("Non-space character F1", lambda m: percent(m["character_f1"])),
        ("Logical calls", lambda m: str(m["counts"]["logical_calls"])),
        ("Calls with reported usage", lambda m: fraction(m, "calls_with_usage", "logical_calls")),
        ("Reported total tokens", lambda m: str((m["reported_tokens"] or {}).get("total_tokens", "unavailable"))),
        ("Median answer time (seconds)", lambda m: f"{m['median_answer_seconds']:.1f}"),
    ]
    lines = ["# Whole-answer audit: saved measurements", "",
             "Generated by `python scripts/verification/answer_report.py`. Interpret with the [experiment report](verification-v0.5-answer-audit.md).", "",
             "24 source-disjoint RAGTruth training answers; 12 annotated-error / 12 unmarked. Both methods use the same Flash profile and inputs, but unequal numbers of calls.", "",
             "| Measure | Direct | Extract + verify |", "|---|---:|---:|"]
    lines.extend(f"| {label} | {get(direct)} | {get(split)} |" for label, get in columns)
    lines += ["", "All annotated errors remain in the denominator, including unextracted errors and execution failures. Overlap measures location, not semantic completeness. Unmarked-answer flags are disagreements with the reference annotations, not automatically adjudicated errors.", "",
              "## Paired answers", "", "The two hit counts below require at least half of each original error span's non-space characters. A flag on an unmarked answer is shown explicitly.", "",
              "| Response | Source | Gold error spans | Direct hits | Split hits | Direct flagged claims | Split flagged claims | Status (direct / split) |",
              "|---|---|---:|---:|---:|---:|---:|---|"]
    paired = {s: {r["response_id"]: r for r in metrics[s]["per_answer"]} for s in ("direct", "split")}
    for case in cases:
        a, b = paired["direct"][case["id"]], paired["split"][case["id"]]
        lines.append(f"| {case['id']} | {case['source_id']} | {a['gold_spans']} | {a['hit_half']} | {b['hit_half']} | {a['flagged_claims']} | {b['flagged_claims']} | {a['status']} / {b['status']} |")
    lines += ["", "## Run metadata", "", f"- Started: {run['started_utc']}", f"- Completed: {run['completed_utc']}",
              f"- Requested model: `{run['settings']['model']}`", f"- Implicit-world-truth spans, retained as source-unsupported: {direct['counts']['implicit_true_spans']}",
              f"- Response model identifiers, direct: `{json.dumps(direct['response_models'])}`",
              f"- Response model identifiers, split: `{json.dumps(split['response_models'])}`", "",
              "Provider identifiers are observations, not authenticated weight identities. Timings include network/provider latency; tokens are provider-reported. The SDK allows one automatic transport retry; counts are logical calls. No Pro fallback or manual retry selected the displayed judgments.", "",
              "60 official test source groups remain reserved and unexecuted. Public-data pretraining exposure is unknown. This is a development diagnostic, not a medical reliability estimate.", ""]
    args.output.write_text("\n".join(lines), encoding="utf8")
    print(args.output)


if __name__ == "__main__":
    main()
